### ISSUE TITLE
prepare doesnt work.

### ISSUE THREAD

**Issue by giorgiozoppi** [Erroneous1/sqlpp11-connector-odbc#19]
Prepare doesnt work. I have to specify the prepare_select. Looks there are missing bytes

 _auto querystring = prepare_quote_query (quotation);
 auto query= sqlpp::custom_query (sqlpp::verbatim(prepare_quote_query(quotation)));
 std::cout << "QUERY TO BE EXECUTED: " << querystring << std::endl;  
    rating::RateTable table;
    // auto result2 = (*_db) (query).with_result_type_of(select(all_of(table)));
    auto p = db->prepare_select(query);_

root@Giorgio:/home/giorgio/redis/redisperformance# make
Scanning dependencies of target test_rateservice
[ 12%] Building CXX object CMakeFiles/test_rateservice.dir/test/test_rate_executor.cpp.o
[ 25%] Building CXX object CMakeFiles/test_rateservice.dir/src/rate_executor.cpp.o
In file included from /usr/local/include/sqlpp11/odbc/odbc.h:31,
                 from /home/giorgio/redis/redisperformance/include/rate_executor.h:4,
                 from /home/giorgio/redis/redisperformance/src/rate_executor.cpp:20:
/usr/local/include/sqlpp11/odbc/connection.h: In instantiation of ‘decltype (((sqlpp::odbc::connection*)this)->sqlpp::odbc::connection::_prepare(t, typename sqlpp::prepare_check<sqlpp::odbc::serializer_t, T, void>::type::type{})) sqlpp::odbc::connection::prepare(const T&) [with T = sqlpp::custom_query_t<void, sqlpp::verbatim_t<sqlpp::no_value_t> >; decltype (((sqlpp::odbc::connection*)this)->sqlpp::odbc::connection::_prepare(t, typename sqlpp::prepare_check<sqlpp::odbc::serializer_t, T, void>::type::type{})) = sqlpp::prepared_execute_t<sqlpp::odbc::connection, sqlpp::custom_query_t<void, sqlpp::verbatim_t<sqlpp::no_value_t> > >]’:
/home/giorgio/redis/redisperformance/src/rate_executor.cpp:91:31:   required from here
/usr/local/include/sqlpp11/odbc/connection.h:253:56: error: ‘_’ is not a member of ‘sqlpp::prepare_check_t<sqlpp::odbc::serializer_t, sqlpp::custom_query_t<void, sqlpp::verbatim_t<sqlpp::no_value_t> > >’ {aka ‘sqlpp::consistent_t’}
     sqlpp::prepare_check_t<_serializer_context_t, T>::_();
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

**Comment by Erroneous1** [comment]
Sorry for such a late reply. Did you ever get this working? Were you trying to execute a query that doesn't have a result?

**Comment by giorgiozoppi** [comment]
If you want work with me to make it work, i am fine. so creating some catch testing, cleaning your code and donate the code Roland. At the end, due to the timining we move to Java for that project, then i left the company. The idea was use native code for caching database results since we wanted to scale alot in terms of requests, but it was flawed because of we used stored procedures.

**Comment by giorgiozoppi** [comment]
Nowadays it will be interesting how your code works with SQL Server.
