### ISSUE TITLE
Better return failure return types

### ISSUE THREAD

**Issue by rbock** [Erroneous1/sqlpp11-connector-odbc#2]
Hi,

MSVC users had a hard time debugging certain sqlpp11 errors, since MSVC did not run into the same static_assert as other compilers. As a result
- I needed to find a better error reporting strategy
- I am giving a talk about this at CppCon and MeetingC++ :-)
- I just pushed a new release of sqlpp11 that is using more differentiated failure return types.

This has a small impact on the connector libraries as well. You should update your code like this:

See https://github.com/rbock/sqlpp11-connector-sqlite3/commit/f2cd30364a96e84d277cef82ae4922883c40a003

Best,

Roland

**Comment by Erroneous1** [comment]
Fixed in 0.03

Looking forward to your CppCon 2016 talk. How much has changed since last year's talk? I didn't discover CppCon until I clicked your links in sqlpp11 and have been slowly watching many of the youtube videos.

**Comment by rbock** [comment]
It is a new talk. I think it would be fair to call is a sequel. After reducing the spew, this is about actually making sure that the right things happen in erroneous situations.
